name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: 📦 打包项目
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: 下载项目依赖
        run: npm install

      - name: 构建项目
        run: npm run build
